# Generated by Django 3.2 on 2023-06-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20230603_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shoppingcarts',
            field=models.ManyToManyField(related_name='recipesinshoppingcart', through='recipes.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Списки покупок'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='recipesinfavorites', through='recipes.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Списки избранного'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcarts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
