# Generated by Django 3.2 on 2023-06-04 19:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230604_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeToIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('ingridient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recipes', to='recipes.ingredient', verbose_name='Ингридиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeToIngridient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeToIngredient', to='recipes.Ingredient', verbose_name='Ингридиенты'),
        ),
    ]
