# Generated by Django 3.2 on 2023-06-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_ingridient_recieptoingredient_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetoingredient',
            options={'verbose_name': 'Связь ингридиентов с рецептами', 'verbose_name_plural': 'Связь ингридиентов с рецептами'},
        ),
        migrations.AlterModelOptions(
            name='recipetotag',
            options={'verbose_name': 'Связь рецептов с тегами', 'verbose_name_plural': 'Связь рецептов с тегами'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipetoingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='recipetoingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingridients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcarts_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
