# Generated by Django 3.2 on 2023-06-15 20:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230614_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=200, samples=None, unique=True, verbose_name='Цвет HEX'),
        ),
    ]
