# Generated by Django 3.2 on 2023-06-15 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_auto_20230615_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='recipesinfavorites', through='recipes.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Списки избранного'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shoppingcarts',
            field=models.ManyToManyField(related_name='recipesinshoppingcart', through='recipes.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Списки покупок'),
        ),
    ]
