# Generated by Django 3.2 on 2023-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_subscriptions_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='uniqie_subscriber_subscription',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscription'), name='unique_subscriber_subscription'),
        ),
    ]
