# Generated by Django 3.2 on 2023-06-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recieps', '0007_auto_20230604_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recieptoingredient',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
